services:
  grafana:
    image: grafana/grafana
    container_name: artio_grafana
    environment:
      # user is `admin`
      - GF_SECURITY_ADMIN_PASSWORD=supersecret
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
  db:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: artio_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: artio_db
    ports:
      - "5000:5432"
    volumes:
      - artio_insight_data:/var/lib/postgresql/data

volumes:
  artio_insight_data:
  grafana_data:
