services:

  renderer:
    image: grafana/grafana-image-renderer:latest
    pull_policy: always
    restart: always
    container_name: ${GF_CONTAINER_NAME}-renderer

  grafana:
    image: grafana/grafana
    container_name: ${GF_CONTAINER_NAME}
    pull_policy: always
    depends_on:
      - database
    ports:
      - ${GF_PORT}:3000
    restart: always
    volumes:
      - artio_insight_gf_data:/var/lib/grafana
    env_file:
        - ./.env

  database:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${DB_CONTAINER_NAME}
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - ${DB_PORT}:${DOCKER_DB_PORT}
    restart: always
    volumes:
      - artio_insight_db_data:/var/lib/postgresql/data
    networks:
      - artio_insights_network

networks:
  artio_insights_network:
    driver: bridge


volumes:
  artio_insight_gf_data:
  artio_insight_db_data:
