services:
  grafana:
    image: grafana/grafana
    container_name: ${GF_CONTAINER_NAME}
    depends_on:
      - database
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GF_PASSWORD}
    ports:
      - ${GF_PORT}:3000
    restart: always
    volumes:
      - artio_insight_gf_data:/var/lib/grafana

  database:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${DB_CONTAINER_NAME}
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - ${DB_PORT}:${DOCKER_DB_PORT}
    restart: always
    volumes:
      - artio_insight_db_data:/var/lib/postgresql/data
    networks:
      - artio_insights_network

  niptags:
    build:
      context: ./
      dockerfile: ./nostr-protocol-nips_nip-tags/Dockerfile
    container_name: niptags
    depends_on:
      - database
    ports:
      - 8080:8080
    networks:
      - artio_insights_network

networks:
  artio_insights_network:
    driver: bridge


volumes:
  artio_insight_gf_data:
  artio_insight_db_data:
