services:
  db:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: artio_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: artio_db
    ports:
      - "5432:5432"
    volumes:
      - artio_data:/var/lib/postgresql/data

volumes:
  artio_data:
