services:
  grafana:
    image: grafana/grafana
    container_name: ${GF_CONTAINER_NAME}
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GF_PASSWORD}
    ports:
      - ${GF_PORT}:3000
    volumes:
      - artio_insight_gf_data:/var/lib/grafana

  database:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${DB_CONTAINER_NAME}
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - artio_insight_db_data:/var/lib/postgresql/data

volumes:
  artio_insight_gf_data:
  artio_insight_db_data:
